export const MEDICAL_SPECIALTIES_RETHUS = [
  "Alergología",
  "Anestesiología y Medicina Perioperatoria",
  "Cardiología",
  "Cardiología Pediátrica",
  "Cirugía Cardiovascular",
  "Cirugía de Cabeza y Cuello",
  "Cirugía de Mano",
  "Cirugía de Tórax",
  "Cirugía de Trasplantes",
  "Cirugía General",
  "Cirugía Oncológica",
  "Cirugía Pediátrica",
  "Cirugía Plástica, Estética y Reconstructiva",
  "Cirugía Vascular",
  "Coloproctología",
  "Dermatología",
  "Dolor y Cuidado Paliativo",
  "Electrofisiología Cardíaca",
  "Endocrinología",
  "Endocrinología Pediátrica",
  "Gastroenterología",
  "Gastroenterología Pediátrica",
  "Genética Médica",
  "Geriatría",
  "Ginecología y Obstetricia",
  "Hematología",
  "Hemato-Oncología Pediátrica",
  "Hepatología",
  "Infectología",
  "Infectología Pediátrica",
  "Mastología",
  "Medicina Aeroespacial",
  "Medicina Crítica y Cuidado Intensivo",
  "Medicina Crítica y Cuidado Intensivo Pediátrico",
  "Medicina de Emergencias",
  "Medicina del Deporte",
  "Medicina del Trabajo y Ambiental",
  "Medicina Familiar",
  "Medicina Física y Rehabilitación",
  "Medicina Forense",
  "Medicina Interna",
  "Medicina Maternofetal",
  "Medicina Nuclear",
  "Nefrología",
  "Nefrología Pediátrica",
  "Neonatología",
  "Neumología",
  "Neumología Pediátrica",
  "Neurocirugía",
  "Neurología",
  "Neurología Pediátrica",
  "Nutrición Clínica",
  "Oftalmología",
  "Oncología Clínica",
  "Oncología Radioterápica",
  "Ortopedia y Traumatología",
  "Ortopedia Pediátrica",
  "Otología y Neurotología",
  "Otorrinolaringología",
  "Otorrinolaringología Pediátrica",
  "Patología Anatómica y Clínica",
  "Pediatría",
  "Perinatología",
  "Psiquiatría",
  "Psiquiatría de Niños y Adolescentes",
  "Radiología e Imágenes Diagnósticas",
  "Reumatología",
  "Urología"
].sort((a, b) => a.localeCompare(b, "es", { sensitivity: "base" }));
